version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    # container_name: foodgram_backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    # container_name: foodgram_frontend
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - ./frontend/:/app/result_build/

  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - db
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/app/media
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf

  # nginx:
  #   container_name: foodgram_gateway
  #   image: nginx:1.25.4-alpine
  #   ports:
  #     - "7000:80"
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   #   - ../frontend/build:/usr/share/nginx/html/
  #   #   - ../docs/:/usr/share/nginx/html/api/docs/
  #   depends_on:
  #       - db
  #       - backend
  #       - frontend
  #   volumes:
  #       - static:/static
  #       - media:/app/media