# Generated by Django 4.2.17 on 2025-01-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shoppingcart_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipestatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipestatus',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipestatus',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
        migrations.DeleteModel(
            name='RecipeStatus',
        ),
    ]
