# Generated by Django 4.2.17 on 2025-01-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_cart',
        ),
    ]
