# Generated by Django 4.2.17 on 2025-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientinrecipe_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('subscribed_to')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
