# Generated by Django 4.2.17 on 2024-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ownuser_avatar_ownuser_is_subscribed_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='users/avatars/'),
        ),
    ]
