# Generated by Django 4.2.17 on 2024-12-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ownuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/avatars/'),
        ),
    ]
