# Generated by Django 4.2.17 on 2024-12-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_ingredient_options_alter_ownuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
