# Generated by Django 4.2.17 on 2024-12-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
