# Generated by Django 4.2.17 on 2024-12-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_tag_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownuser',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
