# Generated by Django 4.2.17 on 2024-12-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_ownuser_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
    ]
