# Generated by Django 4.2.17 on 2024-12-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_recipe_options_rename_title_recipe_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientInRecipe',
        ),
    ]
