# Generated by Django 4.2.17 on 2025-01-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_recipestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestatus',
            name='created_at',
        ),
    ]
