# Generated by Django 4.2.17 on 2025-01-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_recipestatus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/'),
        ),
    ]
