# Generated by Django 4.2.17 on 2025-01-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_ownuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ['recipe'], 'verbose_name': 'Ингредиенты в Рецептах', 'verbose_name_plural': 'Ингредиенты в Рецептах'},
        ),
    ]
