# Generated by Django 4.2.17 on 2025-01-02 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.IntegerField(max_length=64, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
