# Generated by Django 4.2.17 on 2025-01-04 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ManyToManyField(through='users.ShoppingCart', to=settings.AUTH_USER_MODEL),
        ),
    ]
